## Local Python Portfolio analysis

In [3]:

pip install yfinance --upgrade --no-cache-dir

Collecting yfinance
  Downloading yfinance-0.2.36-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\users\timmer\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from yfinance) (2.1.1)
Requirement already satisfied: numpy>=1.16.5 in c:\users\timmer\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from yfinance) (1.26.1)
Collecting requests>=2.31 (from yfinance)
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Collecting lxml>=4.9.1 (from yfinance)
  Downloading lxml-5.1.0-cp310-cp310-win_amd64.whl.metadata (3.6 kB)
Collecting appdirs>=1.4.4 (from yfinance)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: pytz>=2022.5 in c:\users\timmer\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from yfinance) (2023.3.post1)
Collecting frozendict>=2.3.4 (from yfinance)
  Downloading frozendict-2.4.0-cp310-cp310-win_amd64.whl.metadata (23 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-3.17.1.tar.gz (3.0 MB)
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     --- ------------------------------------ 0.2/3.0 MB 5.0 MB/s eta 0:00:01
     ---- ----------------------------------- 0.3/3.0 MB 3.7 MB/s eta 0:00:01
     ------ --------------------------------- 0.5/3.0 MB 3.4 MB/s eta 0:00:01
     --------- ------------------------------ 0.7/3.0 MB 3.9 MB/s eta 0:00:01
     ------------ --------------------------- 0.9/3.0 MB 4.2 MB/s eta 0:00:01
     -------------- ------------------------- 1.0/3.0 MB 3.7 MB/s eta 0:00:01
     ---------------- ----------------------- 1.2/3.0 MB 3.8 MB/s eta 0:00:01
     -------------------- ------------------- 1.5/3.0 MB 4.0 MB/s eta 0:00:01
     --------------------- ------------------ 1.6/3.0 MB 4.0 MB/s eta 0:00:01
     ------------------------ --------------- 1.8/3.0 MB 4.0 MB/s eta 0:00:01
     -------------------------- ------------- 2.0/3.0 MB 3.8 MB/s eta 0:00:01
     ------------------------------ --------- 2.3/3.0 MB 4.0 MB/s eta 0:00:01
     ----------------------------------- ---- 2.6/3.0 MB 4.1 MB/s eta 0:00:01
     ---------------------------------------  2.9/3.0 MB 4.3 MB/s eta 0:00:01
     ---------------------------------------- 3.0/3.0 MB 4.3 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting beautifulsoup4>=4.11.1 (from yfinance)
  Downloading beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting html5lib>=1.1 (from yfinance)
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ---------------------------------------- 0.0/112.2 kB ? eta -:--:--
     ---------- ----------------------------- 30.7/112.2 kB ? eta -:--:--
     -------------------------------------- 112.2/112.2 kB 2.2 MB/s eta 0:00:00
Collecting soupsieve>1.2 (from beautifulsoup4>=4.11.1->yfinance)
  Downloading soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: six>=1.9 in c:\users\timmer\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Collecting webencodings (from html5lib>=1.1->yfinance)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\timmer\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\timmer\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\timmer\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests>=2.31->yfinance) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\timmer\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\timmer\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests>=2.31->yfinance) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\timmer\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests>=2.31->yfinance) (2022.12.7)
Downloading yfinance-0.2.36-py2.py3-none-any.whl (72 kB)
   ---------------------------------------- 0.0/72.4 kB ? eta -:--:--
   ---------------------------------------- 72.4/72.4 kB ? eta 0:00:00
Downloading beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
   ---------------------------------------- 0.0/147.9 kB ? eta -:--:--
   ---------------------------------------- 147.9/147.9 kB 4.4 MB/s eta 0:00:00
Downloading frozendict-2.4.0-cp310-cp310-win_amd64.whl (36 kB)
Downloading lxml-5.1.0-cp310-cp310-win_amd64.whl (3.9 MB)
   ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
   -- ------------------------------------- 0.2/3.9 MB 7.4 MB/s eta 0:00:01
   --- ------------------------------------ 0.4/3.9 MB 4.6 MB/s eta 0:00:01
   ----- ---------------------------------- 0.6/3.9 MB 4.6 MB/s eta 0:00:01
   ------- -------------------------------- 0.7/3.9 MB 3.9 MB/s eta 0:00:01
   -------- ------------------------------- 0.8/3.9 MB 3.9 MB/s eta 0:00:01
   --------- ------------------------------ 1.0/3.9 MB 3.8 MB/s eta 0:00:01
   ------------- -------------------------- 1.3/3.9 MB 4.0 MB/s eta 0:00:01
   --------------- ------------------------ 1.5/3.9 MB 4.1 MB/s eta 0:00:01
   ---------------- ----------------------- 1.6/3.9 MB 3.8 MB/s eta 0:00:01
   ------------------ --------------------- 1.8/3.9 MB 3.8 MB/s eta 0:00:01
   ------------------- -------------------- 1.9/3.9 MB 3.6 MB/s eta 0:00:01
   --------------------- ------------------ 2.1/3.9 MB 3.7 MB/s eta 0:00:01
   ------------------------ --------------- 2.4/3.9 MB 3.9 MB/s eta 0:00:01
   -------------------------- ------------- 2.6/3.9 MB 4.0 MB/s eta 0:00:01
   ----------------------------- ---------- 2.9/3.9 MB 4.0 MB/s eta 0:00:01
   -------------------------------- ------- 3.1/3.9 MB 4.2 MB/s eta 0:00:01
   --------------------------------- ------ 3.3/3.9 MB 4.1 MB/s eta 0:00:01
   ------------------------------------ --- 3.5/3.9 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 3.8/3.9 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 3.9/3.9 MB 4.2 MB/s eta 0:00:00
Downloading requests-2.31.0-py3-none-any.whl (62 kB)
   ---------------------------------------- 0.0/62.6 kB ? eta -:--:--
   ---------------------------------------- 62.6/62.6 kB ? eta 0:00:00
Downloading soupsieve-2.5-py3-none-any.whl (36 kB)
Building wheels for collected packages: peewee
  Building wheel for peewee (pyproject.toml): started
  Building wheel for peewee (pyproject.toml): finished with status 'done'
  Created wheel for peewee: filename=peewee-3.17.1-py3-none-any.whl size=136948 sha256=7ccb7c9d3fd05113a3001fcdffe202d7f848963fe59df7ecfa0ab36d08769810
  Stored in directory: C:\Users\timmer\AppData\Local\Temp\pip-ephem-wheel-cache-zc72bsmq\wheels\d7\35\5c\1374782be033462df5f40174d8d879519d64ed8c25a1977554
Successfully built peewee
Installing collected packages: webencodings, peewee, multitasking, appdirs, soupsieve, requests, lxml, html5lib, frozendict, beautifulsoup4, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.28.1
    Uninstalling requests-2.28.1:
      Successfully uninstalled requests-2.28.1
Successfully installed appdirs-1.4.4 beautifulsoup4-4.12.3 frozendict-2.4.0 html5lib-1.1 lxml-5.1.0 multitasking-0.0.11 peewee-3.17.1 requests-2.31.0 soupsieve-2.5 webencodings-0.5.1 yfinance-0.2.36
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: C:\Users\timmer\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [43]:
import yfinance as yf


def get_quote_info(ticker):
    print(f"collecting data for: {ticker}")
    ticker_info = yf.Ticker(f"{ticker}")
    if debug:
        print(ticker_info.info)

    

    #ask_price = ticker_info.info['ask']
    # dividend_rate = ticker_info.info['dividendRate']
    # dividend_yield = ticker_info.info['dividendYield']
    # payout_ratio = ticker_info.info['payoutRatio']
    # pe_rate = ticker_info.info['forwardPE'] # price / earnings rate
    # fiveYearAvgDividendYield
    # beta
    # trailingPE
    # marketCap
    # currency
    # profitMargins
    # bookValue
    # priceToBook
    # earningsQuarterlyGrowth
    # trailingEps
    # forwardEps
    # pegRatio
    # enterpriseToRevenue
    # enterpriseToEbitda
    # shortName
    # currentPrice
    # recommendationMean
    # recommendationKey
    # quickRatio
    # currentRatio
    # debutToEquity
    # revenuePerShare
    # returnOnAssets
    # returnOnEquity
    # earningsGrowth
    # revenueGrowth
    # grossMargins
    # ebitdaMargings
    # operatingMargings
    # trailingPegRatio
    return ticker_info.info

In [36]:
# single testcase
debug = True
get_quote_info("MSFT")
debug = False

MSFT
{'address1': 'One Microsoft Way', 'city': 'Redmond', 'state': 'WA', 'zip': '98052-6399', 'country': 'United States', 'phone': '425 882 8080', 'website': 'https://www.microsoft.com', 'industry': 'Software - Infrastructure', 'industryKey': 'software-infrastructure', 'industryDisp': 'Software - Infrastructure', 'sector': 'Technology', 'sectorKey': 'technology', 'sectorDisp': 'Technology', 'longBusinessSummary': 'Microsoft Corporation develops and supports software, services, devices and solutions worldwide. The Productivity and Business Processes segment offers office, exchange, SharePoint, Microsoft Teams, office 365 Security and Compliance, Microsoft viva, and Microsoft 365 copilot; and office consumer services, such as Microsoft 365 consumer subscriptions, Office licensed on-premises, and other office services. This segment also provides LinkedIn; and dynamics business solutions, including Dynamics 365, a set of intelligent, cloud-based applications across ERP, CRM, power apps, and power automate; and on-premises ERP and CRM applications. The Intelligent Cloud segment offers server products and cloud services, such as azure and other cloud services; SQL and windows server, visual studio, system center, and related client access licenses, as well as nuance and GitHub; and enterprise services including enterprise support services, industry solutions, and nuance professional services. The More Personal Computing segment offers Windows, including windows OEM licensing and other non-volume licensing of the Windows operating system; Windows commercial comprising volume licensing of the Windows operating system, windows cloud services, and other Windows commercial offerings; patent licensing; and windows Internet of Things; and devices, such as surface, HoloLens, and PC accessories. Additionally, this segment provides gaming, which includes Xbox hardware and content, and first- and third-party content; Xbox game pass and other subscriptions, cloud gaming, advertising, third-party disc royalties, and other cloud services; and search and news advertising, which includes Bing, Microsoft News and Edge, and third-party affiliates. The company sells its products through OEMs, distributors, and resellers; and directly through digital marketplaces, online, and retail stores. The company was founded in 1975 and is headquartered in Redmond, Washington.', 'fullTimeEmployees': 221000, 'companyOfficers': [{'maxAge': 1, 'name': 'Mr. Satya  Nadella', 'age': 56, 'title': 'Chairman & CEO', 'yearBorn': 1967, 'fiscalYear': 2023, 'totalPay': 9276400, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Bradford L. Smith LCA', 'age': 64, 'title': 'President & Vice Chairman', 'yearBorn': 1959, 'fiscalYear': 2023, 'totalPay': 3591277, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Amy E. Hood', 'age': 51, 'title': 'Executive VP & CFO', 'yearBorn': 1972, 'fiscalYear': 2023, 'totalPay': 3452196, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Judson B. Althoff', 'age': 50, 'title': 'Executive VP & Chief Commercial Officer', 'yearBorn': 1973, 'fiscalYear': 2023, 'totalPay': 3355797, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Christopher David Young', 'age': 51, 'title': 'Executive Vice President of Business Development, Strategy & Ventures', 'yearBorn': 1972, 'fiscalYear': 2023, 'totalPay': 2460507, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Alice L. Jolla', 'age': 56, 'title': 'Corporate VP & Chief Accounting Officer', 'yearBorn': 1967, 'fiscalYear': 2023, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. James Kevin Scott', 'age': 51, 'title': 'Executive VP of AI & CTO', 'yearBorn': 1972, 'fiscalYear': 2023, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Brett  Iversen', 'title': 'Vice President of Investor Relations', 'fiscalYear': 2023, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Hossein  Nowbar', 'title': 'Chief Legal Officer', 'fiscalYear': 2023, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Frank X. Shaw', 'title': 'Chief Communications Officer', 'fiscalYear': 2023, 'exercisedValue': 0, 'unexercisedValue': 0}], 'auditRisk': 2, 'boardRisk': 5, 'compensationRisk': 2, 'shareHolderRightsRisk': 2, 'overallRisk': 1, 'governanceEpochDate': 1706745600, 'compensationAsOfEpochDate': 1703980800, 'maxAge': 86400, 'priceHint': 2, 'previousClose': 404.06, 'open': 407.96, 'dayLow': 398.01, 'dayHigh': 404.45, 'regularMarketPreviousClose': 404.06, 'regularMarketOpen': 407.96, 'regularMarketDayLow': 398.01, 'regularMarketDayHigh': 404.45, 'dividendRate': 3.0, 'dividendYield': 0.0074, 'exDividendDate': 1707868800, 'payoutRatio': 0.2523, 'fiveYearAvgDividendYield': 0.98, 'beta': 0.899, 'trailingPE': 36.1626, 'forwardPE': 29.986517, 'volume': 9627060, 'regularMarketVolume': 9627060, 'averageVolume': 24937826, 'averageVolume10days': 22286910, 'averageDailyVolume10Day': 22286910, 'bid': 401.38, 'ask': 401.4, 'bidSize': 1000, 'askSize': 900, 'marketCap': 2974553735168, 'fiftyTwoWeekLow': 245.61, 'fiftyTwoWeekHigh': 420.82, 'priceToSalesTrailing12Months': 13.070193, 'fiftyDayAverage': 388.6076, 'twoHundredDayAverage': 348.3632, 'trailingAnnualDividendRate': 2.86, 'trailingAnnualDividendYield': 0.0070781563, 'currency': 'USD', 'enterpriseValue': 3032717983744, 'profitMargins': 0.36269, 'floatShares': 7418993357, 'sharesOutstanding': 7430439936, 'sharesShort': 49875453, 'sharesShortPriorMonth': 51394982, 'sharesShortPreviousMonthDate': 1703808000, 'dateShortInterest': 1706659200, 'sharesPercentSharesOut': 0.0067000003, 'heldPercentInsiders': 0.00056, 'heldPercentInstitutions': 0.73810995, 'shortRatio': 1.98, 'shortPercentOfFloat': 0.0067000003, 'impliedSharesOutstanding': 7430439936, 'bookValue': 32.06, 'priceToBook': 12.486588, 'lastFiscalYearEnd': 1688083200, 'nextFiscalYearEnd': 1719705600, 'mostRecentQuarter': 1703980800, 'earningsQuarterlyGrowth': 0.332, 'netIncomeToCommon': 82541002752, 'trailingEps': 11.07, 'forwardEps': 13.35, 'pegRatio': 2.13, 'lastSplitFactor': '2:1', 'lastSplitDate': 1045526400, 'enterpriseToRevenue': 13.326, 'enterpriseToEbitda': 25.608, '52WeekChange': 0.5991609, 'SandP52WeekChange': 0.25222528, 'lastDividendValue': 0.75, 'lastDividendDate': 1707868800, 'exchange': 'NMS', 'quoteType': 'EQUITY', 'symbol': 'MSFT', 'underlyingSymbol': 'MSFT', 'shortName': 'Microsoft Corporation', 'longName': 'Microsoft Corporation', 'firstTradeDateEpochUtc': 511108200, 'timeZoneFullName': 'America/New_York', 'timeZoneShortName': 'EST', 'uuid': 'b004b3ec-de24-385e-b2c1-923f10d3fb62', 'messageBoardId': 'finmb_21835', 'gmtOffSetMilliseconds': -18000000, 'currentPrice': 400.32, 'targetHighPrice': 546.44, 'targetLowPrice': 298.1, 'targetMeanPrice': 455.86, 'targetMedianPrice': 455.0, 'recommendationMean': 1.7, 'recommendationKey': 'buy', 'numberOfAnalystOpinions': 44, 'totalCash': 80981999616, 'totalCashPerShare': 10.899, 'ebitda': 118427000832, 'totalDebt': 111358001152, 'quickRatio': 1.096, 'currentRatio': 1.218, 'totalRevenue': 227583000576, 'debtToEquity': 46.736, 'revenuePerShare': 30.612, 'returnOnAssets': 0.1519, 'returnOnEquity': 0.39174, 'freeCashflow': 58680999936, 'operatingCashflow': 102646996992, 'earningsGrowth': 0.332, 'revenueGrowth': 0.176, 'grossMargins': 0.69815004, 'ebitdaMargins': 0.52037, 'operatingMargins': 0.43585998, 'financialCurrency': 'USD', 'trailingPegRatio': 2.3694}

In [40]:
# stocks to analyze
stocks = [
    ('AAPL') #Apple
    ,('MSFT') # Microsoft
    ,('NVDA') # Nvidia
    ,('AMD') # Advanced Micro Devices Inc.
    ,('BUD') # Anheuser-Busch InBev
    ,('V') # VISA
    ,('AMZN') # Amazon
    ,('META') # Facebook
    ,('WMT') # Walmart
    ,('NSRGY') # Nestle
    ,('UNA.AS') # Unilever
    ,('DANOY') # Danone
    ,('OR.PA') # L'oreal
    ,
]

In [44]:
# maybe build in a wait to not irritate yahoo?
import pandas as pd

debug = False
results = []

for ticker in stocks:
    result = get_quote_info(ticker)
    results.append(result)

# only create dataframe at the end to speedup process
df = pd.DataFrame(results)

AAPL
MSFT
NVDA
AMD
BUD
V
AMZN
META
WMT
NSRGY
UNA.AS
DANOY
OR.PA

In [45]:
# see all data collected
display(df)

,address1,city,state,zip,country,phone,website,industry,industryKey,industryDisp,...,operatingCashflow,earningsGrowth,revenueGrowth,grossMargins,ebitdaMargins,operatingMargins,financialCurrency,trailingPegRatio,fax,address2
0,One Apple Park Way,Cupertino,CA,95014,United States,408 996 1010,https://www.apple.com,Consumer Electronics,consumer-electronics,Consumer Electronics,...,1.164330e+11,0.160,0.021,0.45027,0.33733,0.33764,USD,2.2780,NaN,NaN
1,One Microsoft Way,Redmond,WA,98052-6399,United States,425 882 8080,https://www.microsoft.com,Software - Infrastructure,software-infrastructure,Software - Infrastructure,...,1.026470e+11,0.332,0.176,0.69815,0.52037,0.43586,USD,2.3694,NaN,NaN
2,2788 San Tomas Expressway,Santa Clara,CA,95051,United States,408 486 2000,https://www.nvidia.com,Semiconductors,semiconductors,Semiconductors,...,1.883900e+10,12.741,2.055,0.69853,0.49389,0.57489,USD,0.7079,NaN,NaN
3,2485 Augustine Drive,Santa Clara,CA,95054,United States,408 749 4000,https://www.amd.com,Semiconductors,semiconductors,Semiconductors,...,1.667000e+09,48.693,0.102,0.50273,0.16993,0.05545,USD,0.7248,NaN,NaN
4,Brouwerijplein 1,Leuven,NaN,3000,Belgium,32 1 627 61 11,https://www.ab-inbev.com,Beverages - Brewers,beverages-brewers,Beverages - Brewers,...,NaN,0.025,0.032,0.54044,0.30035,0.25722,USD,2.5966,32 1 650 61 11,NaN
5,PO Box 8999,San Francisco,CA,94128-8999,United States,650 432 3200,https://www.visa.com,Credit Services,credit-services,Credit Services,...,2.019800e+10,0.203,0.088,0.97784,0.70229,0.69064,USD,1.7202,NaN,NaN
6,410 Terry Avenue North,Seattle,WA,98109-5210,United States,206 266 1000,https://www.aboutamazon.com,Internet Retail,internet-retail,Internet Retail,...,8.494600e+10,50.693,0.139,0.46982,0.14878,0.07525,USD,2.4542,NaN,NaN
7,1 Meta Way,Menlo Park,CA,94025,United States,650 543 4800,https://investor.fb.com,Internet Content & Information,internet-content-information,Internet Content & Information,...,7.111300e+10,2.002,0.247,0.80722,0.44613,0.40727,USD,1.0764,NaN,NaN
8,702 South West 8th Street,Bentonville,AR,72716,United States,479 273 4000,https://www.stock.walmart.com,Discount Stores,discount-stores,Discount Stores,...,3.215700e+10,NaN,0.052,0.24272,0.05897,0.03857,USD,2.9548,NaN,NaN
9,avenue NestlE 55,Vevey,NaN,1800,Switzerland,41 21 924 11 11,https://www.nestle.com,Packaged Foods,packaged-foods,Packaged Foods,...,1.371300e+10,0.104,0.016,0.45251,0.19362,0.16804,CHF,2.3556,NaN,NaN
10,Unilever House,London,NaN,EC4Y 0DY,United Kingdom,44 20 7438 2800,https://www.unilever.com,Household & Personal Products,household-personal-products,Household & Personal Products,...,9.426000e+09,-0.377,-0.042,1.00000,0.19588,0.16524,EUR,33.5500,NaN,100 Victoria Embankment
11,"17, Boulevard Haussmann",Paris,NaN,75009,France,33 1 44 35 20 20,https://www.danone.com,Packaged Foods,packaged-foods,Packaged Foods,...,3.418000e+09,0.489,0.063,0.46507,0.14960,0.12240,EUR,3.6820,NaN,NaN
12,"41, rue Martre",Clichy,NaN,92117,France,33 1 47 56 70 00,https://www.loreal.com,Household & Personal Products,household-personal-products,Household & Personal Products,...,7.604600e+09,0.143,0.036,0.73855,0.22846,0.16667,EUR,4.2601,NaN,NaN

In [46]:
# specify what columns to keep
df = df[['shortName','industry']]
display(df)

                          shortName                        industry
0                        Apple Inc.            Consumer Electronics
1             Microsoft Corporation       Software - Infrastructure
2                NVIDIA Corporation                  Semiconductors
3      Advanced Micro Devices, Inc.                  Semiconductors
4   Anheuser-Busch Inbev SA Sponsor             Beverages - Brewers
5                         Visa Inc.                 Credit Services
6                  Amazon.com, Inc.                 Internet Retail
7              Meta Platforms, Inc.  Internet Content & Information
8                      Walmart Inc.                 Discount Stores
9   NESTLE SA SPON ADR EACH REPR 1                   Packaged Foods
10                     UNILEVER PLC   Household & Personal Products
11  DANONE ADR-EA CNV INTO 1/5 EUR0                  Packaged Foods
12                          L'OREAL   Household & Personal Products